// Generated by CoffeeScript 1.10.0
(function() {
  var app, express, io, minify, nsq, r, sendData, server;

  express = require('express');

  app = express();

  server = require('http').Server(app);

  io = require('socket.io')(server);

  nsq = require('nsqjs');

  r = require('rethinkdb');

  minify = require('express-minify');

  server.listen(8000);

  app.use(minify());

  app.use(express["static"]('public'));

  app.get('/', function(req, res) {
    res.sendfile(__dirname + '/index.html');
  });

  sendData = function(socket) {
    return r.connect({
      db: "dadog",
      host: "rethinkdb-driver"
    }).then(function(conn) {
      return r.db('dadog').table('bets').filter(r.row('time').gt(r.now())).group('competition_token').orderBy(r.asc(r.row('meta')('created_at'))).run(conn);
    }).then(function(groups) {
      return groups.each(function(err, group) {
        var bets;
        if (err) {
          throw err;
        }
        bets = group['reduction'];
        return bets.forEach(function(bet) {
          return socket.emit('update', bet);
        });
      });
    }).done();
  };

  io.on('connection', function(socket) {
    var reader;
    reader = new nsq.Reader('update', 'site', {
      nsqdTCPAddresses: 'nsqd:4150'
    });
    sendData(socket);
    reader.connect();
    reader.on('message', function(msg) {
      io.emit('update', msg.json());
      msg.finish();
    });
  });

}).call(this);
